# -*- coding: utf-8 -*-
"""machine deployment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DkngHjBABdwnjJr9ofdz9NhqSSnD_dB_
"""

import streamlit as st
import joblib
import pandas as pd

model = joblib.load("machine_model.pkl")

st.title("Machine Failure Prediction")

footfall = st.number_input("Footfall")
tempMode = st.number_input("Temperature Mode")
AQ = st.number_input("Air Quality")
USS = st.number_input("Ultrasonic Sensor")
CS = st.number_input("Current Sensor")
VOC = st.number_input("VOC Sensor")
RP = st.number_input("RPM Sensor")
IP = st.number_input("IP Sensor")
Temperature = st.number_input("Temperature")

input_data = pd.DataFrame({
    'footfall': [footfall],
    'tempMode': [tempMode],
    'AQ': [AQ],
    'USS': [USS],
    'CS': [CS],
    'VOC': [VOC],
    'RP': [RP],
    'IP': [IP],
    'Temperature': [Temperature]
})

if st.button("Predict"):
    prediction = model.predict(input_data)

    if prediction[0] == 1:
        st.error(" Machine Failure Detected!")
    else:
        st.success("Machine is Working Normally")
